import dotenv from 'dotenv';

dotenv.config();

const { DATABASE_STRING, DATABASE_PASSWORD, PORT, JWT_SECRET, JWT_EXPIRES_IN, JWT_COOKIE_EXPIRES_IN, NODE_ENV } = process.env;

export { DATABASE_STRING, DATABASE_PASSWORD, PORT, JWT_SECRET, JWT_EXPIRES_IN, JWT_COOKIE_EXPIRES_IN, NODE_ENV };